services:
  wiremock:
    image: wiremock/wiremock:3.12.1
    ports:
      - "8585:8080"
    volumes:
      - ./_wiremock/mappings:/home/wiremock/mappings
      - ./_wiremock/__files:/home/wiremock/__files
    command: "--verbose --global-response-templating"
